/* This file is generated by scripts/generate-article-content-registry.mjs. */
import article0 from '../../../../content/2025-in-review-ml-books-career-writing/en/index.mdx?raw';
import article1 from '../../../../content/2025-in-review-ml-books-career-writing/pt-BR/index.mdx?raw';

import type { Locale } from '@/types/Locale';

export const articleContent: Record<string, Partial<Record<Locale, string>>> = {
  '2025-in-review-ml-books-career-writing': {
    en: article0,
    'pt-BR': article1,
  },
};
